spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: mksd-test-client

eureka:
 client:
  service-url:
    defaultZone: http://admin:windawn@localhost:7001/eureka
---
server:
  port: 8102
spring:
  profiles: beta
  application:
      name: mksd-test-client

eureka:
 client:
  service-url:
    defaultZone: http://admin:windawn@localhost:7001/eureka
